language: cpp

os: linux 

notifications:
  email: false
  # webhooks: https://www.travisbuddy.com/

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

matrix:
  include:
    - name: Compile and ctest
      stage: build
      env: STEP=compile_and_test

before_script:
  - if [ "$STEP" = "compile_and_test" ]; then
        docker pull dealii/dealii:master-focal;
    fi

script:
  - if [ "$STEP" = "compile_and_test" ]; then
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then 
         docker run -i -t dealii/dealii:master-focal /bin/sh -c "git clone https://github.com/$TRAVIS_REPO_SLUG hyperdeal && cd hyperdeal && git checkout $TRAVIS_BRANCH && mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release && make -j2 && ctest -V";
      else
         docker run -i -t dealii/dealii:master-focal /bin/sh -c "git clone https://github.com/$TRAVIS_PULL_REQUEST_SLUG hyperdeal && cd hyperdeal && git checkout $TRAVIS_PULL_REQUEST_BRANCH && mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release && make -j2 && ctest -V";
      fi
    fi
 