name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
         git remote -v
         git branch -a
         echo "github.event_path      " ${{ github.event_path }}
         echo "github.workflow        " ${{ github.workflow }}
         echo "github.job             " ${{ github.job }}
         echo "github.run_id          " ${{ github.run_id }}
         echo "github.run_number      " ${{ github.run_number }}
         echo "github.actor           " ${{ github.actor }}
         echo "github.repository      " ${{ github.repository }}
         echo "github.repository_owner" ${{ github.repository_owner }}
         echo "github.event_name      " ${{ github.event_name }}
         echo "github.sha             " ${{ github.sha }}
         echo "github.ref             " ${{ github.ref }}
         echo "github.head_ref        " ${{ github.head_ref }}
         echo "github.base_ref        " ${{ github.base_ref }}
         echo "github.token           " ${{ github.token }}
         echo "github.workspace       " ${{ github.workspace }}
         echo "github.action          " ${{ github.action }}
         echo "github.action_path     " ${{ github.action_path }}

         docker pull dealii/dealii:master-focal
         echo "docker run -t dealii/dealii:master-focal /bin/sh -c \"git clone https://github.com/${{ github.repository }} && cd hyperdeal && git fetch origin ${{ github.ref }} && git checkout FETCH_HEAD && git --no-pager  log | head -n50 && mkdir build && cd build && cmake .. && make -j2 && ctest -V\"";
         docker run -t dealii/dealii:master-focal /bin/sh -c "git clone https://github.com/${{ github.repository }} && cd hyperdeal && git fetch origin ${{ github.ref }} && git checkout FETCH_HEAD && git --no-pager  log | head -n50 && mkdir build && cd build && cmake .. && make -j2 && ctest -V";
